version: "3.9"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      # Modify this value to point to your MongoDB instance (local or remote)
      MONGODB_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    volumes:
      - .:/app
      - nextjs_cache:/app/.next/cache

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
  nextjs_cache: